red_polymers = [
    "Acetophenone/Oxymethylene Copolymer",
    "Acetylenediurea/Formaldehyde/Tosylamide Crosspolymer",
    "Acrolein/Acrylic Acid Copolymer",
    "Acrylamide/Ammonium Acrylate Copolymer",
    "Acrylamide/Ethalkonium Chloride Acrylate Copolymer",
    "Acrylamide/Ethyltrimonium Chloride Acrylate/Ethalkonium Chloride",
    "Acrylate Copolymer",
    "Acrylamide/Sodium Acrylate Copolymer",
    "Acrylamide/Sodium Acryloyldimethyltaurate Copolymer",
    "Acrylamide/Sodium Acryloyldimethyltaurate/Acrylic Acid Copolymer",
    "Acrylamides/DMAPA Acrylates/Methoxy PEG Methacrylate Copolymer",
    "Acrylamidopropyltrimonium Chloride/Acrylates Copolymer",
    "Acrylates Copolymer",
    "Acrylates Crosspolymer",
    "Acrylates Crosspolymer-3",
    "Acrylates Crosspolymer-4",
    "Acrylates/Acetoacetoxyethyl Methacrylate Copolymer",
    "Acrylates/Acrylamide Copolymer",
    "Acrylates/Aminoacrylates/C10-30 Alkyl PEG-20 Itaconate Copolymer",
    "Acrylates/Ammonium Methacrylate Copolymer",
    "Acrylates/Beheneth-25 Methacrylate Copolymer",
    "Acrylates/Beheneth-25 Methacrylate/Steareth-30 Methacrylate Copolymer",
    "Acrylates/Behenyl Acrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Behenyl Methacrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Bis-Hydroxypropyl Dimethicone Crosspolymer",
]

red_polymers.extend([
    "Acrylates/C1-2 Succinates/Hydroxyacrylates Copolymer",
    "Acrylates/C10-30 Alkyl Acrylate Crosspolymer",
    "Acrylates/C10-30 Alkyl Methacrylate Copolymer",
    "Acrylates/C12-13 Alkyl Methacrylates/Methoxyethyl Acrylate Crosspolymer",
    "Acrylates/C12-22 Alkyl Methacrylate Copolymer",
    "Acrylates/C26-29 Olefin Copolymer",
    "Acrylates/C5-8 Alkyl Acrylate Copolymer",
    "Acrylates/Carbamate Copolymer",
    "Acrylates/Ceteareth-20 Methacrylate Crosspolymer",
    "Acrylates/Ceteareth-25 Methacrylate/Methacrylamide Crosspolymer",
    "Acrylates/Ceteth-20 Itaconate Copolymer",
    "Acrylates/Ceteth-20 Methacrylate Copolymer",
    "Acrylates/Diacetoneacrylamide Copolymer",
    "Acrylates/Diethylaminoethyl Methacrylate/Ethylhexyl Acrylate Copolymer",
    "Acrylates/Dimethicone Copolymer",
    "Acrylates/Dimethicone Methacrylate Copolymer",
    "Acrylates/Dimethicone Methacrylate/Ethylhexyl Acrylate Copolymer",
    "Acrylates/Dimethiconol Acrylate Copolymer",
    "Acrylates/Dimethylaminoethyl Methacrylate Copolymer",
    "Acrylates/Ethylamine Oxide Methacrylate Copolymer",
    "Acrylates/Ethylhexyl Acrylate Copolymer",
    "Acrylates/Ethylhexyl Acrylate Crosspolymer",
    "Acrylates/Ethylhexyl Acrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Ethylhexyl Acrylate/Glycidyl Methacrylate Crosspolymer",
    "Acrylates/Ethylhexyl Acrylate/Hema Copolymer",
    "Acrylates/Ethylhexyl Acrylate/Hema/Styrene Copolymer",
    "Acrylates/Ethylhexyl Acrylate/Styrene Copolymer",
    "Acrylates/Ethylhexylacrylamide Copolymer",
    "Acrylates/Hydroxyesters Acrylates Copolymer",
    "Acrylates/Hydroxyethyl Acrylate/Lauryl Acrylate Copolymer",
    "Acrylates/Hydroxyethyl Acrylate/Methoxyethyl Acrylate Copolymer",
    "Acrylates/Laureth-25 Methacrylate Copolymer",
    "Acrylates/Lauryl Acrylate/Stearyl Acrylate/Ethylamine Oxide Methacrylate Copolymer"
])

red_polymers.extend([
    "Acrylates/Lauryl Methacrylate Copolymer",
    "Acrylates/Lauryl Methacrylate/Tridecyl Methacrylate Crosspolymer",
    "Acrylates/Methacrylamide Copolymer",
    "Acrylates/Methoxy PEG-15 Methacrylate Copolymer",
    "Acrylates/Methoxy PEG-23 Methacrylate Copolymer",
    "Acrylates/Methoxy PEG-23 Methacrylate/Perfluorootyl Ethyl Acrylate Copolymer",
    "Acrylates/Methoxy PEG-4 Methacrylate Copolymer",
    "Acrylates/Octylacrylamide Copolymer",
    "Acrylates/Octylacrylamide/Diphenyl Amodimethicone Copolymer",
    "Acrylates/Palmeth-25 Acrylate Copolymer",
    "Acrylates/Palmeth-25 Itaconate Copolymer",
    "Acrylates/PEG-10 Maleate/Styrene Copolymer",
    "Acrylates/PEG-4 Dimethacrylate Crosspolymer",
    "Acrylates/Polytrimethylsiloxymethacrylate Copolymer",
    "Acrylates/Propyl Trimethicone Methacrylate Copolymer",
    "Acrylates/Rhus Verniciflua Sap Extract Crosspolymer",
    "Acrylates/Steareth-20 Itaconate Copolymer",
    "Acrylates/Steareth-20 Methacrylate Copolymer",
    "Acrylates/Steareth-20 Methacrylate Crosspolymer",
    "Acrylates/Steareth-30 Methacrylate Copolymer",
    "Acrylates/Steareth-50 Acrylate Copolymer",
    "Acrylates/Stearyl Acrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Stearyl Acrylate/Ethylamine Oxide Methacrylate Copolymer",
    "Acrylates/Stearyl Methacrylate Copolymer",
    "Acrylates/T-Butylacrylamide Copolymer",
    "Acrylates/TDI/Trimethylolpropane Copolymer",
    "Acrylates/Tridecyl Acrylate/Triethoxysilylpropyl Methacrylate/Dimethicone Methacrylate Copolymer",
    "Acrylates/Trifluoropropylmethacrylate/Polytrimethyl Siloxymethacrylate Copolymer",
    "Acrylates/Tris(Trimethylsiloxy)Silylpropyl Methacrylate Copolymer",
    "Acrylates/VA Copolymer",
    "Acrylates/VA Crosspolymer"
])

red_polymers.extend([
    "Acrylates/Vinyl Isodecanoate Crosspolymer",
    "Acrylates/Vinyl Neodecanoate Crosspolymer",
    "Acrylates/VP Copolymer",
    "Acrylates/VP/Dimethylaminoethyl Methacrylate/Diacetone",
    "Acrylamide/Hydroxypropyl Acrylate Copolymer",
    "Acrylic Acid/Acrylamidomethyl Propane Sulfonic Acid Copolymer",
    "Acrylic Acid/Acrylonitrogens Copolymer",
    "Acrylic Acid/C12-22 Alkyl Acrylate Copolymer",
    "Acrylic Acid/Isobornyl Methacrylate/Isobutyl Methacrylate Copolymer",
    "Acrylic Acid/Isobutyl Acrylate/Isobornyl Acrylate Copolymer",
    "Acrylic Acid/Phosphorylcholine Glycol Acrylate Crosspolymer",
    "Acrylic Acid/Stearyl Acrylate Copolymer",
    "Acrylic Acid/Stearyl Methacrylate/Dimethicone Methacrylate Copolymer",
    "Acrylonitrile/Butadiene/Styrene Copolymer",
    "Acrylonitrile/Glycol Dimethacrylate Crosspolymer",
    "Acrylonitrile/Methacrylonitrile/Methyl Methacrylate Copolymer",
    "Acrylonitrile/Methyl Methacrylate/Vinylidene Chloride Copolymer",
    "Acryloyl Dimethyl Taurate/Melamine/PEG-Methacrylate Crosspolymer",
    "Acryloyl Dimethyl Taurate/Melamine/PEG-6 Methacrylate/Phloroglucinol Crosspolymer",
    "Allyl Methacrylate/Glycol Dimethacryate Crosspolymer",
    "Allyl Methacrylates Crosspolymer",
    "Allyl Stearate/VA Copolymer",
    "Aminoethylacrylate Phosphate/Acrylates Copolymer",
    "Aminoethylpropanediol-Acrylates/Acrylamide Copolymer",
    "Aminoethylpropanediol-Ampd-Acrylates/Diacetoneacrylamide Copolymer",
    "Ammonium Acrylates Copolymer",
    "Ammonium Acrylates/Acrylonitrogens Copolymer",
    "Ammonium Acrylates/Ethylhexyl Acrylate Copolymer",
    "Ammonium Acrylates/Methyl Styrene/Styrene Copolymer",
    "Ammonium Acryloyl Dimethyltaurate/Carboxyethyl Acrylate Crosspolymer",
    "Ammonium Acryloyldimethyltaurate/Beheneth-25 Methacrylate Crosspolymer",
    "Ammonium Acryloyldimethyltaurate/Laureth-7 Methacrylate Copolymer",
    "Ammonium Acryloyldimethyltaurate/Steareth-25 Methacrylate"
])

red_polymers.extend([
    "Ammonium Acryloyldimethyltaurate/Steareth-8 Methacrylate Copolymer",
    "Ammonium Acryloydimethyltaurate/Vinyl Formamide Copolymer",
    "Ammonium Polyacrylate",
    "Ammonium Styrene/Acrylates Copolymer",
    "Ammonium Styrene/Acrylates/Ethylhexyl Acrylate/Lauryl Acrylate Copolymer",
    "Ammonium VA/Acrylates Copolymer",
    "AMP-Acrylate/C1-18 Alkyl Acrylates/C1-8 Alkyl Acrylamide Copolymer",
    "AMP-Acrylates Copolymer",
    "AMP-Acrylates/Allyl Methacrylate Copolymer",
    "AMP-Acrylates/C1-18 Alkyl Acrylate/C1-8 Alkyl Acrylamide Copolymer",
    "Acrylamide/Hydroxyethylacrylate Copolymer",
    "AMP-Acrylates/Diacetoneacrylamide Copolymer",
    "AMP-Acrylates/Dimethylaminoethylmethacrylate Copolymer",
    "AMP-Acrylates/Ethylhexyl Acrylate Copolymer",
    "AMPD-Acrylates/Diacetoneacrylamide Copolymer",
    "Behenyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Behenyl Methacrylate/Ethylamine Oxide Methacrylate Copolymer",
    "Behenyl Methacrylate/Perfluorooctylethyl Methacrylate Copolymer",
    "Behenyl Methacrylate/T-Butyl Methacrylate Copolymer",
    "Bis-Hydroxyethyl Acrylate Poly(Neopentyl Glycol Adipate)/Ipdi Copolymer",
    "Bis-Hydroxyethyl Acrylate Polyneopentyl Glycol Adipate/Tdi Copolymer",
    "Bis-Hydroxypropylmethacrylate Poly(1,4-Butanediol)-9/Ipdi Copolymer",
    "Bis-Pentaerythrityl Diacrylate/Ipdi Copolymer",
    "Bis-Vinyl Diphenyl Dimethicone",
    "Bis-Vinyldimethicone Crosspolymer",
    "Butene/Propylene Copolymer",
    "Butyl Acrylate/C6-14 Perfluoroalkylethyl Acrylate/Mercaptopropyl Dimethicone Copolymer",
    "Butyl Acrylate/Cyclohexyl Methacrylate Copolymer",
    "Butyl Acrylate/Ethylhexyl Methacrylate Copolymer",
    "Butyl Acrylate/Ethyltrimonium Chloride Methacrylate/Styrene Copolymer",
    "Butyl Acrylate/Glycol Dimethacrylate Crosspolymer"
])

red_polymers.extend([
    "Butyl Acrylate/Hydroxyethyl Methacrylate Copolymer",
    "Butyl Acrylate/Hydroxypropyl Dimethicone Acrylate Copolymer",
    "Butyl Acrylate/Isopropylacrylamide/PEG-18 Dimethacrylate Crosspolymer",
    "Butyl Acrylate/Styrene Copolymer",
    "Butyl Benzoic Acid/Phthalic Anhydride/Trimethylolethane Copolymer",
    "Butyl Dimethicone Acrylate/Cyclohexylmethacrylate/Ethylhexyl Acrylate Copolymer",
    "Butyl Ester Of Ethylene/MA Copolymer",
    "Butyl Ester Of PVM/MA Copolymer",
    "Butyl Methacrylate/DMAPA Acrylates/Vinylacetamide Crosspolymer",
    "Butyl Polydimethylsiloxyl Ethylene/Propylene/Vinylnorbornene Copolymer",
    "Butylaminoethyl Methacrylate Crosspolymer",
    "Butyldimethicone Methacrylate/Methyl Methacrylate Crosspolymer",
    "Butylene/Ethylene Copolymer",
    "Butylene/Ethylene/Propylene Copolymer",
    "Butylene/Ethylene/Styrene Copolymer",
    "C12-22 Alkyl Acrylate/Hydroxyethylacrylate Copolymer",
    "C18-22 Alkyl PEG-25 Methacrylate/Diethylaminoethyl Methacrylate Copolymer",
    "C20-24 Olefin/Oleyl Alcohol Copolymer",
    "C26-28 Alkyldimethylsilyl Polypropylsilsesquioxane",
    "C30-38 Olefin/Isopropyl Maleate/MA Copolymer",
    "C4-6 Olefin/Styrene Copolymer",
    "C6-14 Perfluoroalkylethyl Acrylate/Hema Copolymer",
    "C8-22 Alkyl Acrylate/Butyl Dimethicone Methacrylate Copolymer",
    "C8-22 Alkyl Acrylates/Methacrylic Acid Crosspolymer",
    "Carbomer",
    "Carbomer 940",
    "Cetearyl Dimethicone/Vinyl Dimethicone Crosspolymer",
    "Cetyl Dimethicone",
    "Cetyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Cetyl Hexacosyl Dimethicone/Bis-Vinyldimethicone Crosspolymer",
    "Corn Starch/Acrylamide/Sodium Acrylate Copolymer"
])

#On page 7/19 for red flags
#steps -> Grab rest by taking pics and breaking down structure. (red polymer list)
#


print(red_polymers)